// <auto-generated />
using System;
using InspectionTracker.MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InspectionTracker.MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260320013005_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("InspectionTracker.Domain.FollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InspectionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.ToTable("FollowUps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DueDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            InspectionId = 2
                        },
                        new
                        {
                            Id = 2,
                            DueDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            InspectionId = 4
                        },
                        new
                        {
                            Id = 3,
                            DueDate = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            InspectionId = 6
                        },
                        new
                        {
                            Id = 4,
                            DueDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            InspectionId = 10
                        },
                        new
                        {
                            Id = 5,
                            ClosedDate = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            DueDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            InspectionId = 3
                        },
                        new
                        {
                            Id = 6,
                            ClosedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            DueDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            InspectionId = 7
                        },
                        new
                        {
                            Id = 7,
                            ClosedDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DueDate = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            InspectionId = 9
                        },
                        new
                        {
                            Id = 8,
                            DueDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            InspectionId = 11
                        },
                        new
                        {
                            Id = 9,
                            DueDate = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            InspectionId = 12
                        },
                        new
                        {
                            Id = 10,
                            DueDate = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            InspectionId = 13
                        });
                });

            modelBuilder.Entity("InspectionTracker.Domain.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PremisesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PremisesId");

                    b.ToTable("Inspections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InspectionDate = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Good",
                            Outcome = "Pass",
                            PremisesId = 1,
                            Score = 90
                        },
                        new
                        {
                            Id = 2,
                            InspectionDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Issues found",
                            Outcome = "Fail",
                            PremisesId = 1,
                            Score = 55
                        },
                        new
                        {
                            Id = 3,
                            InspectionDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "OK",
                            Outcome = "Pass",
                            PremisesId = 2,
                            Score = 70
                        },
                        new
                        {
                            Id = 4,
                            InspectionDate = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Recheck needed",
                            Outcome = "Fail",
                            PremisesId = 3,
                            Score = 65
                        },
                        new
                        {
                            Id = 5,
                            InspectionDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Good",
                            Outcome = "Pass",
                            PremisesId = 4,
                            Score = 88
                        },
                        new
                        {
                            Id = 6,
                            InspectionDate = new DateTime(2026, 1, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Serious issues",
                            Outcome = "Fail",
                            PremisesId = 5,
                            Score = 45
                        },
                        new
                        {
                            Id = 7,
                            InspectionDate = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Excellent",
                            Outcome = "Pass",
                            PremisesId = 6,
                            Score = 92
                        },
                        new
                        {
                            Id = 8,
                            InspectionDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "OK",
                            Outcome = "Pass",
                            PremisesId = 7,
                            Score = 78
                        },
                        new
                        {
                            Id = 9,
                            InspectionDate = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Good",
                            Outcome = "Pass",
                            PremisesId = 8,
                            Score = 82
                        },
                        new
                        {
                            Id = 10,
                            InspectionDate = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Poor",
                            Outcome = "Fail",
                            PremisesId = 9,
                            Score = 50
                        },
                        new
                        {
                            Id = 11,
                            InspectionDate = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Excellent",
                            Outcome = "Pass",
                            PremisesId = 10,
                            Score = 95
                        },
                        new
                        {
                            Id = 12,
                            InspectionDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "OK",
                            Outcome = "Pass",
                            PremisesId = 11,
                            Score = 60
                        },
                        new
                        {
                            Id = 13,
                            InspectionDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "OK",
                            Outcome = "Pass",
                            PremisesId = 12,
                            Score = 72
                        },
                        new
                        {
                            Id = 14,
                            InspectionDate = new DateTime(2025, 5, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Bad",
                            Outcome = "Fail",
                            PremisesId = 2,
                            Score = 40
                        },
                        new
                        {
                            Id = 15,
                            InspectionDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Good",
                            Outcome = "Pass",
                            PremisesId = 3,
                            Score = 85
                        },
                        new
                        {
                            Id = 16,
                            InspectionDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Good",
                            Outcome = "Pass",
                            PremisesId = 4,
                            Score = 90
                        },
                        new
                        {
                            Id = 17,
                            InspectionDate = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "OK",
                            Outcome = "Pass",
                            PremisesId = 5,
                            Score = 77
                        },
                        new
                        {
                            Id = 18,
                            InspectionDate = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "OK",
                            Outcome = "Pass",
                            PremisesId = 6,
                            Score = 66
                        },
                        new
                        {
                            Id = 19,
                            InspectionDate = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Issues",
                            Outcome = "Fail",
                            PremisesId = 7,
                            Score = 58
                        },
                        new
                        {
                            Id = 20,
                            InspectionDate = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Good",
                            Outcome = "Pass",
                            PremisesId = 8,
                            Score = 80
                        },
                        new
                        {
                            Id = 21,
                            InspectionDate = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Good",
                            Outcome = "Pass",
                            PremisesId = 9,
                            Score = 90
                        },
                        new
                        {
                            Id = 22,
                            InspectionDate = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Issues",
                            Outcome = "Fail",
                            PremisesId = 10,
                            Score = 55
                        },
                        new
                        {
                            Id = 23,
                            InspectionDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Good",
                            Outcome = "Pass",
                            PremisesId = 11,
                            Score = 88
                        },
                        new
                        {
                            Id = 24,
                            InspectionDate = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "OK",
                            Outcome = "Pass",
                            PremisesId = 12,
                            Score = 60
                        },
                        new
                        {
                            Id = 25,
                            InspectionDate = new DateTime(2026, 1, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Notes = "Bad",
                            Outcome = "Fail",
                            PremisesId = 1,
                            Score = 45
                        });
                });

            modelBuilder.Entity("InspectionTracker.Domain.Premises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Premises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Main St 1",
                            Name = "Cafe Roma",
                            RiskRating = "High",
                            Town = "Dublin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Main St 2",
                            Name = "Fresh Bites",
                            RiskRating = "Medium",
                            Town = "Dublin"
                        },
                        new
                        {
                            Id = 3,
                            Address = "High Rd 5",
                            Name = "Golden Dragon",
                            RiskRating = "Low",
                            Town = "Dublin"
                        },
                        new
                        {
                            Id = 4,
                            Address = "River St 10",
                            Name = "Cork Grill",
                            RiskRating = "High",
                            Town = "Cork"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Harbour Rd 3",
                            Name = "Cork Sushi",
                            RiskRating = "Medium",
                            Town = "Cork"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Market Sq 7",
                            Name = "Cork Bakery",
                            RiskRating = "Low",
                            Town = "Cork"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Ocean Ave 2",
                            Name = "Galway Diner",
                            RiskRating = "High",
                            Town = "Galway"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Old Town 4",
                            Name = "Galway Pizza",
                            RiskRating = "Medium",
                            Town = "Galway"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Harbour St 8",
                            Name = "Galway Cafe",
                            RiskRating = "Low",
                            Town = "Galway"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Main St 9",
                            Name = "Dublin BBQ",
                            RiskRating = "High",
                            Town = "Dublin"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Green Rd 11",
                            Name = "Cork Vegan",
                            RiskRating = "Low",
                            Town = "Cork"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Hill Rd 6",
                            Name = "Galway Steakhouse",
                            RiskRating = "Medium",
                            Town = "Galway"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InspectionTracker.Domain.FollowUp", b =>
                {
                    b.HasOne("InspectionTracker.Domain.Inspection", "Inspection")
                        .WithMany("FollowUps")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("InspectionTracker.Domain.Inspection", b =>
                {
                    b.HasOne("InspectionTracker.Domain.Premises", "Premises")
                        .WithMany("Inspections")
                        .HasForeignKey("PremisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Premises");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InspectionTracker.Domain.Inspection", b =>
                {
                    b.Navigation("FollowUps");
                });

            modelBuilder.Entity("InspectionTracker.Domain.Premises", b =>
                {
                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
